# データサイエンス100本ノック（構造化データ加工編） - R

## はじめに
- 初めに以下のセルを実行してください
- 必要なライブラリのインポートとデータベース（PostgreSQL）からのデータ読み込みを行います
- 利用が想定されるライブラリは以下セルでインポートしています
- その他利用したいライブラリがあればinstall.packages()で適宜インストールしてください
- 名前、住所等はダミーデータであり、実在するものではありません

In [3]:
require("RPostgreSQL")
require("tidyr")
require("dplyr")
require("stringr")
require("caret")
require("lubridate")
require("rsample")
require("recipes")
require("themis")

host <- "db"
port <- Sys.getenv()["PG_PORT"]
dbname <- Sys.getenv()["PG_DATABASE"]
user <- Sys.getenv()["PG_USER"]
password <- Sys.getenv()["PG_PASSWORD"]

con <- dbConnect(PostgreSQL(), host=host, port=port, dbname=dbname, user=user, password=password)
df_customer <- dbGetQuery(con,"SELECT * FROM customer")
df_category <- dbGetQuery(con,"SELECT * FROM category")
df_product <- dbGetQuery(con,"SELECT * FROM product")
df_receipt <- dbGetQuery(con,"SELECT * FROM receipt")
df_store <- dbGetQuery(con,"SELECT * FROM store")
df_geocode <- dbGetQuery(con,"SELECT * FROM geocode")

Loading required package: RPostgreSQL

Loading required package: DBI

Loading required package: tidyr

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: stringr

Loading required package: caret

Loading required package: ggplot2

Loading required package: lattice

Loading required package: lubridate


Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union


Loading required package: rsample

Loading required package: recipes


Attaching package: ‘recipes’


The following object is masked from ‘package:stringr’:

    fixed


The following object is masked from ‘package:stats’:

    step


Loading required package: themis

# 演習問題

---
> R-001: レシート明細データ（df_receipt）から全項目の先頭10件を表示し、どのようなデータを保有しているか目視で確認せよ。

---
> R-002: レシート明細データ（df_receipt）から売上年月日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、10件表示せよ。

---
> R-003: レシート明細データ（df_receipt）から売上年月日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、10件表示せよ。ただし、sales_ymdsales_dateに項目名を変更しながら抽出すること。

---
> R-004: レシート明細データ（df_receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"

---
> R-005: レシート明細データ（df_receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 売上金額（amount）が1,000以上

---
> R-006: レシート明細データ（df_receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上数量（quantity）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 売上金額（amount）が1,000以上または売上数量（quantity）が5以上

---
> R-007: レシート明細データ（df_receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 売上金額（amount）が1,000以上2,000以下

---
> R-008: レシート明細データ（df_receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 商品コード（product_cd）が"P071401019"以外

---
> R-009: 以下の処理において、出力結果を変えずにORをANDに書き換えよ。

`df_store %>% filter(!(prefecture_cd == "13" | floor_area > 900))`

---
> R-010: 店舗データ（df_store）から、店舗コード（store_cd）が"S14"で始まるものだけ全項目抽出し、10件表示せよ。

---
> R-011: 顧客データ（df_customer）から顧客ID（customer_id）の末尾が1のものだけ全項目抽出し、10件表示せよ。

---
> R-012: 店舗データ（df_store）から、住所 (address) に"横浜市"が含まれるものだけ全項目表示せよ。

---
> R-013: 顧客データ（df_customer）から、ステータスコード（status_cd）の先頭がアルファベットのA〜Fで始まるデータを全項目抽出し、10件表示せよ。

---
> R-014: 顧客データ（df_customer）から、ステータスコード（status_cd）の末尾が数字の1〜9で終わるデータを全項目抽出し、10件表示せよ。

---
> R-015: 顧客データ（df_customer）から、ステータスコード（status_cd）の先頭がアルファベットのA〜Fで始まり、末尾が数字の1〜9で終わるデータを全項目抽出し、10件表示せよ。

---
> R-016: 店舗データ（df_store）から、電話番号（tel_no）が3桁-3桁-4桁のデータを全項目表示せよ。

---
> R-017: 顧客データ（df_customer）を生年月日（birth_day）で高齢順にソートし、先頭から全項目を10件表示せよ。

---
> R-018: 顧客データ（df_customer）を生年月日（birth_day）で若い順にソートし、先頭から全項目を10件表示せよ。

---
> R-019: レシート明細データ（df_receipt）に対し、1件あたりの売上金額（amount）が高い順にランクを付与し、先頭から10件表示せよ。項目は顧客ID（customer_id）、売上金額（amount）、付与したランクを表示させること。なお、売上金額（amount）が等しい場合は同一順位を付与するものとする。

---
> R-020: レシート明細データ（df_receipt）に対し、1件あたりの売上金額（amount）が高い順にランクを付与し、先頭から10件表示せよ。項目は顧客ID（customer_id）、売上金額（amount）、付与したランクを表示させること。なお、売上金額（amount）が等しい場合でも別順位を付与すること。

---
> R-021: レシート明細データ（df_receipt）に対し、件数をカウントせよ。

---
> R-022: レシート明細データ（df_receipt）の顧客ID（customer_id）に対し、ユニーク件数をカウントせよ。

---
> R-023: レシート明細データ（df_receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）と売上数量（quantity）を合計せよ。

---
> R-024: レシート明細データ（df_receipt）に対し、顧客ID（customer_id）ごとに最も新しい売上年月日（sales_ymd）を求め、10件表示せよ。

---
> R-025: レシート明細データ（df_receipt）に対し、顧客ID（customer_id）ごとに最も古い売上年月日（sales_ymd）を求め、10件表示せよ。

---
> R-026: レシート明細データ（df_receipt）に対し、顧客ID（customer_id）ごとに最も新しい売上年月日（sales_ymd）と古い売上年月日を求め、両者が異なるデータを10件表示せよ。

---
> R-027: レシート明細データ（df_receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の平均を計算し、降順でTOP5を表示せよ。

---
> R-028: レシート明細データ（df_receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の中央値を計算し、降順でTOP5を表示せよ。

---
> R-029: レシート明細データ（df_receipt）に対し、店舗コード（store_cd）ごとに商品コード（product_cd）の最頻値を求め、10件表示させよ。

---
> R-030: レシート明細データ（df_receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の分散を計算し、降順で5件表示せよ。

In [15]:
var_sample <- function(x){var(x)*(length(x)-1)/length(x)}

df_receipt |>
    group_by(store_cd) |>
    summarise(var = var_sample(amount)) |>
    arrange(desc(var)) |>
    slice(1:5)

  store_cd var
1 S13052   440088.7
2 S14011   306314.6
3 S14034   296920.1
4 S13001   295432.0
5 S13015   295294.4

---
> R-031: レシート明細データ（df_receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の標準偏差を計算し、降順で5件表示せよ。

In [17]:
var_sample <- function(x){var(x)*(length(x)-1)/length(x)}
sd_sample <- function(x){sqrt(var_sample(x))}

df_receipt |>
    group_by(store_cd) |>
    summarise(sd = sd_sample(amount)) |>
    arrange(desc(sd)) |>
    slice(1:5)

  store_cd sd
1 S13052   663.3918
2 S14011   553.4569
3 S14034   544.9037
4 S13001   543.5366
5 S13015   543.4099

---
> R-032: レシート明細データ（df_receipt）の売上金額（amount）について、25％刻みでパーセンタイル値を求めよ。

In [22]:
df_receipt |>
    summarise(amount_25per = quantile(amount, 0.25),
             amount_50per = quantile(amount, 0.50),
             amount_75per = quantile(amount, 0.75),
             amount_100per = quantile(amount, 1),)

  amount_25per amount_50per amount_75per amount_100per
1 102          170          288          10925

---
> R-033: レシート明細データ（df_receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の平均を計算し、330以上のものを抽出せよ。

In [32]:
df_receipt |>
    group_by(store_cd) |>
    summarise(mean = mean(amount), .groups = "drop")  |>
    filter(mean >= 330)

   store_cd mean
1  S12013   330.1941
2  S13001   348.4704
3  S13003   350.9155
4  S13004   330.9439
5  S13015   351.1120
6  S13019   330.2086
7  S13020   337.8799
8  S13052   402.8675
9  S14010   348.7913
10 S14011   335.7183
11 S14026   332.3406
12 S14045   330.0821
13 S14047   330.0771

---
> R-034: レシート明細データ（df_receipt）に対し、顧客ID（customer_id）ごとに売上金額（amount）を合計して全顧客の平均を求めよ。ただし、顧客IDが"Z"から始まるものは非会員を表すため、除外して計算すること。

In [48]:
df_receipt |>
    filter(!startsWith(customer_id, "Z")) |>
    group_by(customer_id) |>
    summarise(sum_amount = sum(amount), .groups = "drop") |> 
    summarise(mean_amount = mean(sum_amount), .groups = "drop")

  mean_amount
1 2547.742

---
> R-035: レシート明細データ（df_receipt）に対し、顧客ID（customer_id）ごとに売上金額（amount）を合計して全顧客の平均を求め、平均以上に買い物をしている顧客を抽出し、10件表示せよ。ただし、顧客IDが"Z"から始まるものは非会員を表すため、除外して計算すること。

In [72]:
# tar_mean <- df_receipt |>
#     filter(!startsWith(customer_id, "Z")) |>
#     group_by(customer_id) |>
#     summarise(sum_amount = sum(amount), .groups = "drop") |> 
#     summarise(mean_amount = mean(sum_amount), .groups = "drop") |>
#     pull(mean_amount)

# df_receipt |>
#     filter(!startsWith(customer_id, "Z")) |>
#     group_by(customer_id) |>
#     summarise(sum_amount = sum(amount), .groups = "drop") |>
#     filter(sum_amount >= tar_mean) |>
#     slice(1:10)

df_receipt |>
    filter(!startsWith(customer_id, "Z")) |>
    group_by(customer_id) |>
    summarise(sum_amount = sum(amount), .groups = "drop") |>
    filter(sum_amount >= mean(sum_amount)) |>
    slice(1:10)

   customer_id    sum_amount
1  CS001115000010 3044
2  CS001205000006 3337
3  CS001214000009 4685
4  CS001214000017 4132
5  CS001214000052 5639
6  CS001215000040 3496
7  CS001304000006 3726
8  CS001305000005 3485
9  CS001305000011 4370
10 CS001315000180 3300

   customer_id    sum_amount
1  CS001115000010 3044
2  CS001205000006 3337
3  CS001214000009 4685
4  CS001214000017 4132
5  CS001214000052 5639
6  CS001215000040 3496
7  CS001304000006 3726
8  CS001305000005 3485
9  CS001305000011 4370
10 CS001315000180 3300

---
> R-036: レシート明細データ（df_receipt）と店舗データ（df_store）を内部結合し、レシート明細データの全項目と店舗データの店舗名（store_name）を10件表示せよ。

In [77]:
inner_join(df_receipt,
           df_store[c("store_cd", "store_name")], by = "store_cd") |>
    slice(1:10)

   sales_ymd sales_epoch store_cd receipt_no receipt_sub_no customer_id
1  20181103  1541203200  S14006    112       1              CS006214000001
2  20181118  1542499200  S13008   1132       2              CS008415000097
3  20170712  1499817600  S14028   1102       1              CS028414000014
4  20190205  1549324800  S14042   1132       1              ZZ000000000000
5  20180821  1534809600  S14025   1102       2              CS025415000050
6  20190605  1559692800  S13003   1112       1              CS003515000195
7  20181205  1543968000  S14024   1102       2              CS024514000042
8  20190922  1569110400  S14040   1102       1              CS040415000178
9  20170504  1493856000  S13020   1112       2              ZZ000000000000
10 20191010  1570665600  S14027   1102       1              CS027514000015
   product_cd quantity amount store_name
1  P070305012 1        158    葛が谷店
2  P070701017 1         81    成城店
3  P060101005 1        170    二ツ橋店
4  P050301001 1         25    新山下店
5  P060102007 1         90    大和店
6  P050102002 1        138    狛江店
7  P080101005 1         30    三田店
8  P070501004 1        128    長津田店
9  P071302010 1        770    十条仲原店
10 P071101003 1        680    南藤沢店

---
> R-037: 商品データ（df_product）とカテゴリデータ（df_category）を内部結合し、商品データの全項目とカテゴリデータのカテゴリ小区分名（category_small_name）を10件表示せよ。

In [82]:
inner_join(df_product,
          df_category[c("category_small_cd","category_small_name")], by = "category_small_cd") |>
    slice(1:10)

   product_cd category_major_cd category_medium_cd category_small_cd unit_price
1  P040101001 04                0401               040101            198
2  P040101002 04                0401               040101            218
3  P040101003 04                0401               040101            230
4  P040101004 04                0401               040101            248
5  P040101005 04                0401               040101            268
6  P040101006 04                0401               040101            298
7  P040101007 04                0401               040101            338
8  P040101008 04                0401               040101            420
9  P040101009 04                0401               040101            498
10 P040101010 04                0401               040101            580
   unit_cost category_small_name
1  149       弁当類
2  164       弁当類
3  173       弁当類
4  186       弁当類
5  201       弁当類
6  224       弁当類
7  254       弁当類
8  315       弁当類
9  374       弁当類
10 435       弁当類

---
> R-038: 顧客データ（df_customer）とレシート明細データ（df_receipt）から、顧客ごとの売上金額合計を求め、10件表示せよ。ただし、売上実績がない顧客については売上金額を0として表示させること。また、顧客は性別コード（gender_cd）が女性（1）であるものを対象とし、非会員（顧客IDが"Z"から始まるもの）は除外すること。

In [102]:
left_join(df_customer, df_receipt, by = "customer_id") |>
    filter(gender_cd == 1) |>
    filter(!startsWith(customer_id, "Z")) |>
    group_by(customer_id) |>
    summarise(sum_amount = sum(amount, na.rm = TRUE), .groups = "drop") |>
    slice(1:10)

   customer_id    sum_amount
1  CS001112000009    0
2  CS001112000019    0
3  CS001112000021    0
4  CS001112000023    0
5  CS001112000024    0
6  CS001112000029    0
7  CS001112000030    0
8  CS001113000004 1298
9  CS001113000010    0
10 CS001114000005  626

---
> R-039: レシート明細データ（df_receipt）から、売上日数の多い顧客の上位20件を抽出したデータと、売上金額合計の多い顧客の上位20件を抽出したデータをそれぞれ作成し、さらにその2つを完全外部結合せよ。ただし、非会員（顧客IDが"Z"から始まるもの）は除外すること。

In [119]:
df_data <- df_receipt |>
    filter(!startsWith(customer_id, "Z")) |>
    group_by(customer_id)

df_cnt <- df_data |>
    summarise(come_days = n_distinct(sales_ymd), .groups = "drop") |>
    arrange(desc(come_days)) |>
    slice(1:20)

df_sum <- df_data |>
    summarise(sum_amount = sum(amount), .groups = "drop") |>
    arrange(desc(sum_amount)) |>
    slice(1:20)

full_join(df_cnt, df_sum, by = "customer_id")

   customer_id    come_days sum_amount
1  CS040214000008 23           NA
2  CS010214000010 22        18585
3  CS015415000185 22        20153
4  CS010214000002 21           NA
5  CS028415000007 21        19127
6  CS016415000141 20        18372
7  CS017415000097 20        23086
8  CS014214000023 19           NA
9  CS021514000045 19           NA
10 CS021515000172 19           NA
11 CS022515000226 19           NA
12 CS031414000051 19        19202
13 CS039414000052 19           NA
14 CS007515000107 18           NA
15 CS014415000077 18           NA
16 CS021515000056 18           NA
17 CS021515000211 18           NA
18 CS022515000028 18           NA
19 CS030214000008 18           NA
20 CS031414000073 18           NA
21 CS001605000009 NA        18925
22 CS006515000023 NA        18372
23 CS011414000106 NA        18338
24 CS038415000104 NA        17847
25 CS035414000024 NA        17615
26 CS021515000089 NA        17580
27 CS032414000072 NA        16563
28 CS016415000101 NA        16348
29 CS011415000006 NA        16094
30 CS034415000047 NA        16083
31 CS007514000094 NA        15735
32 CS009414000059 NA        15492
33 CS030415000034 NA        15468
34 CS015515000034 NA        15300

---
> R-040: 全ての店舗と全ての商品を組み合わせたデータを作成したい。店舗データ（df_store）と商品データ（df_product）を直積し、件数を計算せよ。

In [123]:
nrow(df_store) * nrow(df_product)

# cross_join(df_store, df_product) |> nrow()

[1] 531590

---
> R-041: レシート明細データ（df_receipt）の売上金額（amount）を日付（sales_ymd）ごとに集計し、前回売上があった日からの売上金額増減を計算せよ。そして結果を10件表示せよ。

In [130]:
df_receipt |>
    group_by(sales_ymd) |>
    summarise(sum_amount = sum(amount)) |>
    mutate(lag_amount = lag(sum_amount),
          diff_amount = sum_amount - lag_amount) |>
    slice(1:10)

   sales_ymd sum_amount lag_amount diff_amount
1  20170101  33723         NA         NA
2  20170102  24165      33723      -9558
3  20170103  27503      24165       3338
4  20170104  36165      27503       8662
5  20170105  37830      36165       1665
6  20170106  32387      37830      -5443
7  20170107  23415      32387      -8972
8  20170108  24737      23415       1322
9  20170109  26718      24737       1981
10 20170110  20143      26718      -6575

---
> R-042: レシート明細データ（df_receipt）の売上金額（amount）を日付（sales_ymd）ごとに集計し、各日付のデータに対し、前回、前々回、3回前に売上があった日のデータを結合せよ。そして結果を10件表示せよ。

In [135]:
df_sum <- df_receipt |>
    group_by(sales_ymd) |>
    summarise(sum_amount = sum(amount), .groups = "drop")

df_sum %>%
  mutate(
    across(c(sales_ymd, sum_amount), 
           list(lag1 = ~lag(.x, 1), lag2 = ~lag(.x, 2), lag3 = ~lag(.x, 3)))
  ) %>%
  drop_na() %>%
  slice(1:10)

   sales_ymd sum_amount sales_ymd_lag1 sales_ymd_lag2 sales_ymd_lag3
1  20170104  36165      20170103       20170102       20170101
2  20170105  37830      20170104       20170103       20170102
3  20170106  32387      20170105       20170104       20170103
4  20170107  23415      20170106       20170105       20170104
5  20170108  24737      20170107       20170106       20170105
6  20170109  26718      20170108       20170107       20170106
7  20170110  20143      20170109       20170108       20170107
8  20170111  24287      20170110       20170109       20170108
9  20170112  23526      20170111       20170110       20170109
10 20170113  28004      20170112       20170111       20170110
   sum_amount_lag1 sum_amount_lag2 sum_amount_lag3
1  27503           24165           33723
2  36165           27503           24165
3  37830           36165           27503
4  32387           37830           36165
5  23415           32387           37830
6  24737           23415           32387
7  26718           24737           23415
8  20143           26718           24737
9  24287           20143           26718
10 23526           24287           20143

---
> R-043: レシート明細データ（df_receipt）と顧客データ（df_customer）を結合し、性別コード（gender_cd）と年代（ageから計算）ごとに売上金額（amount）を合計した売上サマリデータを作成せよ。性別コードは0が男性、1が女性、9が不明を表すものとする。
>
> ただし、項目構成は年代、女性の売上金額、男性の売上金額、性別不明の売上金額の4項目とすること（縦に年代、横に性別のクロス集計）。また、年代は10歳ごとの階級とすること。

In [147]:
df_sales_summary <- df_customer[c("customer_id", "gender_cd", "age")] |>
  mutate(era = trunc(age / 10) * 10) |>
  inner_join(df_receipt, by = "customer_id") |>
  group_by(gender_cd, era) |>
  summarise(sum_amount = sum(amount), .groups = "drop") |>
  pivot_wider(
    names_from = gender_cd,
    values_from = sum_amount,
    values_fill = 0
  ) |>
  rename(male = `0`, female = `1`, unknown = `9`)

df_sales_summary

  era male   female  unknown
1 10    1591  149836   4317
2 20   72940 1363724  44328
3 30  177322  693047  50441
4 40   19355 9320791 483512
5 50   54320 6685192 342923
6 60  272469  987741  71418
7 70   13435   29764   2427
8 80   46360  262923   5111
9 90       0    6260      0

---
> R-044: 043で作成した売上サマリデータ（df_sales_summary）は性別の売上を横持ちさせたものであった。このデータから性別を縦持ちさせ、年代、性別コード、売上金額の3項目に変換せよ。ただし、性別コードは男性を"00"、女性を"01"、不明を"99"とする。

In [148]:
df_sales_summary |>
  pivot_longer(
    cols = c(male, female, unknown), # 縦持ちに戻す列
    names_to = "gender_cd",          # 列名を格納する新しい列名（旧: key）
    values_to = "sum_amount"         # セルの値を格納する新しい列名（旧: value）
  ) |>
  mutate(gender_cd = case_when(
    gender_cd == "male"    ~ "00",
    gender_cd == "female"  ~ "01",
    gender_cd == "unknown" ~ "99"
  ))

   era gender_cd sum_amount
1  10  00           1591
2  10  01         149836
3  10  99           4317
4  20  00          72940
5  20  01        1363724
6  20  99          44328
7  30  00         177322
8  30  01         693047
9  30  99          50441
10 40  00          19355
11 40  01        9320791
12 40  99         483512
13 50  00          54320
14 50  01        6685192
15 50  99         342923
16 60  00         272469
17 60  01         987741
18 60  99          71418
19 70  00          13435
20 70  01          29764
21 70  99           2427
22 80  00          46360
23 80  01         262923
24 80  99           5111
25 90  00              0
26 90  01           6260
27 90  99              0

---
> R-045: 顧客データ（df_customer）の生年月日（birth_day）は日付型でデータを保有している。これをYYYYMMDD形式の文字列に変換し、顧客ID（customer_id）とともに10件表示せよ。

In [155]:
df_customer |>
  mutate(birth_day = format(birth_day, "%Y%m%d")) |>
  select(customer_id, birth_day) |>
  head(10)

   customer_id    birth_day
1  CS021313000114 19810429
2  CS037613000071 19520401
3  CS031415000172 19761004
4  CS028811000001 19330327
5  CS001215000145 19950329
6  CS020401000016 19740915
7  CS015414000103 19770809
8  CS029403000008 19730817
9  CS015804000004 19310502
10 CS033513000180 19620711

---
> R-046: 顧客データ（df_customer）の申し込み日（application_date）はYYYYMMDD形式の文字列型でデータを保有している。これを日付型に変換し、顧客ID（customer_id）とともに10件表示せよ。

In [156]:
df_customer |>
  transmute(
    customer_id,
    application_date = lubridate::ymd(application_date)
  ) |>
  slice_head(n = 10)

   customer_id    application_date
1  CS021313000114 2015-09-05
2  CS037613000071 2015-04-14
3  CS031415000172 2015-05-29
4  CS028811000001 2016-01-15
5  CS001215000145 2017-06-05
6  CS020401000016 2015-02-25
7  CS015414000103 2015-07-22
8  CS029403000008 2015-05-15
9  CS015804000004 2015-06-07
10 CS033513000180 2015-07-28

---
> R-047: レシート明細データ（df_receipt）の売上日（sales_ymd）はYYYYMMDD形式の数値型でデータを保有している。これを日付型に変換し、レシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

In [160]:
df_receipt |>
  transmute(
    receipt_no,
    receipt_sub_no,
    sales_ymd = lubridate::ymd(sales_ymd)
  ) |>
  slice_head(n = 10)

   receipt_no receipt_sub_no sales_ymd
1   112       1              2018-11-03
2  1132       2              2018-11-18
3  1102       1              2017-07-12
4  1132       1              2019-02-05
5  1102       2              2018-08-21
6  1112       1              2019-06-05
7  1102       2              2018-12-05
8  1102       1              2019-09-22
9  1112       2              2017-05-04
10 1102       1              2019-10-10

---
> R-048: レシート明細データ（df_receipt）の売上エポック秒（sales_epoch）は数値型のUNIX秒でデータを保有している。これを日付型に変換し、レシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

---
> R-049: レシート明細データ（df_receipt）の売上エポック秒（sales_epoch）を日付型に変換し、「年」だけ取り出してレシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

---
> R-050: レシート明細データ（df_receipt）の売上エポック秒（sales_epoch）を日付型に変換し、「月」だけ取り出してレシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。なお、「月」は0埋め2桁で取り出すこと。

---
> R-051: レシート明細データ（df_receipt）の売上エポック秒を日付型に変換し、「日」だけ取り出してレシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。なお、「日」は0埋め2桁で取り出すこと。

---
> R-052: レシート明細データ（df_receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計の上、売上金額合計に対して2,000円以下を0、2,000円より大きい金額を1に二値化し、顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

---
> R-053: 顧客データ（df_customer）の郵便番号（postal_cd）に対し、東京（先頭3桁が100〜209のもの）を1、それ以外のものを0に二値化せよ。さらにレシート明細データ（df_receipt）と結合し、全期間において売上実績のある顧客数を、作成した二値ごとにカウントせよ。

---
> R-054:  顧客データ（df_customer）の住所（address）は、埼玉県、千葉県、東京都、神奈川県のいずれかとなっている。都道府県毎にコード値を作成し、顧客ID、住所とともに10件表示せよ。値は埼玉県を11、千葉県を12、東京都を13、神奈川県を14とすること。

---
> R-055: レシート明細（df_receipt）データの売上金額（amount）を顧客ID（customer_id）ごとに合計し、その合計金額の四分位点を求めよ。その上で、顧客ごとの売上金額合計に対して以下の基準でカテゴリ値を作成し、顧客ID、売上金額合計とともに10件表示せよ。カテゴリ値は順に1〜4とする。
>
> - 最小値以上第1四分位未満 ・・・ 1を付与
> - 第1四分位以上第2四分位未満 ・・・ 2を付与
> - 第2四分位以上第3四分位未満 ・・・ 3を付与
> - 第3四分位以上 ・・・ 4を付与

---
> R-056: 顧客データ（df_customer）の年齢（age）をもとに10歳刻みで年代を算出し、顧客ID（customer_id）、生年月日（birth_day）とともに10件表示せよ。ただし、60歳以上は全て60歳代とすること。年代を表すカテゴリ名は任意とする。

---
> R-057: 056の抽出結果と性別コード（gender_cd）により、新たに性別×年代の組み合わせを表すカテゴリデータを作成し、10件表示せよ。組み合わせを表すカテゴリの値は任意とする。

---
> R-058: 顧客データ（df_customer）の性別コード（gender_cd）をダミー変数化し、顧客ID（customer_id）とともに10件表示せよ。

---
> R-059: レシート明細データ（df_receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を平均0、標準偏差1に標準化して顧客ID、売上金額合計とともに10件表示せよ。標準化に使用する標準偏差は、分散の平方根、もしくは不偏分散の平方根のどちらでも良いものとする。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

---
> R-060: レシート明細データ（df_receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を最小値0、最大値1に正規化して顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

---
> R-061: レシート明細データ（df_receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を常用対数化（底10）して顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

---
> R-062: レシート明細データ（df_receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を自然対数化（底e）して顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

---
> R-063: 商品データ（df_product）の単価（unit_price）と原価（unit_cost）から各商品の利益額を算出し、結果を10件表示せよ。

---
> R-064: 商品データ（df_product）の単価（unit_price）と原価（unit_cost）から、各商品の利益率の全体平均を算出せよ。ただし、単価と原価には欠損が生じていることに注意せよ。

---
> R-065: 商品データ（df_product）の各商品について、利益率が30%となる新たな単価を求めよ。ただし、1円未満は切り捨てること。そして結果を10件表示させ、利益率がおよそ30％付近であることを確認せよ。ただし、単価（unit_price）と原価（unit_cost）には欠損が生じていることに注意せよ。

---
> R-066: 商品データ（df_product）の各商品について、利益率が30%となる新たな単価を求めよ。今回は、1円未満を丸めること（四捨五入または偶数への丸めで良い）。そして結果を10件表示させ、利益率がおよそ30％付近であることを確認せよ。ただし、単価（unit_price）と原価（unit_cost）には欠損が生じていることに注意せよ。

---
> R-067: 商品データ（df_product）の各商品について、利益率が30%となる新たな単価を求めよ。今回は、1円未満を切り上げること。そして結果を10件表示させ、利益率がおよそ30％付近であることを確認せよ。ただし、単価（unit_price）と原価（unit_cost）には欠損が生じていることに注意せよ。

---
> R-068: 商品データ（df_product）の各商品について、消費税率10％の税込み金額を求めよ。1円未満の端数は切り捨てとし、結果を10件表示せよ。ただし、単価（unit_price）には欠損が生じていることに注意せよ。

---
> R-069: レシート明細データ（df_receipt）と商品データ（df_product）を結合し、顧客毎に全商品の売上金額合計と、カテゴリ大区分コード（category_major_cd）が"07"（瓶詰缶詰）の売上金額合計を計算の上、両者の比率を求めよ。抽出対象はカテゴリ大区分コード"07"（瓶詰缶詰）の売上実績がある顧客のみとし、結果を10件表示せよ。

---
> R-070: レシート明細データ（df_receipt）の売上日（sales_ymd）に対し、顧客データ（df_customer）の会員申込日（application_date）からの経過日数を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。

---
> R-071: レシート明細データ（df_receipt）の売上日（sales_ymd）に対し、顧客データ（df_customer）の会員申込日（application_date）からの経過月数を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。1ヶ月未満は切り捨てること。

---
> R-072: レシート明細データ（df_receipt）の売上日（df_customer）に対し、顧客データ（df_customer）の会員申込日（application_date）からの経過年数を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。1年未満は切り捨てること。

---
> R-073: レシート明細データ（df_receipt）の売上日（sales_ymd）に対し、顧客データ（df_customer）の会員申込日（application_date）からのエポック秒による経過時間を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（なお、sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。なお、時間情報は保有していないため各日付は0時0分0秒を表すものとする。

---
> R-074: レシート明細データ（df_receipt）の売上日（sales_ymd）に対し、当該週の月曜日からの経過日数を計算し、売上日、直前の月曜日付とともに10件表示せよ（sales_ymdは数値でデータを保持している点に注意）。

---
> R-075: 顧客データ（df_customer）からランダムに1%のデータを抽出し、先頭から10件表示せよ。

---
> R-076: 顧客データ（df_customer）から性別コード（gender_cd）の割合に基づきランダムに10%のデータを層化抽出し、性別コードごとに件数を集計せよ。

---
> R-077: レシート明細データ（df_receipt）の売上金額を顧客単位に合計し、合計した売上金額の外れ値を抽出せよ。なお、外れ値は売上金額合計を対数化したうえで平均と標準偏差を計算し、その平均から3σを超えて離れたものとする（自然対数と常用対数のどちらでも可）。結果は10件表示せよ。

---
> R-078: レシート明細データ（df_receipt）の売上金額（amount）を顧客単位に合計し、合計した売上金額の外れ値を抽出せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。なお、ここでは外れ値を第1四分位と第3四分位の差であるIQRを用いて、「第1四分位数-1.5×IQR」を下回るもの、または「第3四分位数+1.5×IQR」を超えるものとする。結果は10件表示せよ。

---
> R-079: 商品データ（df_product）の各項目に対し、欠損数を確認せよ。

---
> R-080: 商品データ（df_product）のいずれかの項目に欠損が発生しているレコードを全て削除した新たな商品データを作成せよ。なお、削除前後の件数を表示させ、079で確認した件数だけ減少していることも確認すること。

---
> R-081: 単価（unit_price）と原価（unit_cost）の欠損値について、それぞれの平均値で補完した新たな商品データを作成せよ。なお、平均値については1円未満を丸めること（四捨五入または偶数への丸めで良い）。補完実施後、各項目について欠損が生じていないことも確認すること。

---
> R-082: 単価（unit_price）と原価（unit_cost）の欠損値について、それぞれの中央値で補完した新たな商品データを作成せよ。なお、中央値については1円未満を丸めること（四捨五入または偶数への丸めで良い）。補完実施後、各項目について欠損が生じていないことも確認すること。

---
> R-083: 単価（unit_price）と原価（unit_cost）の欠損値について、各商品のカテゴリ小区分コード（category_small_cd）ごとに算出した中央値で補完した新たな商品データを作成せよ。なお、中央値については1円未満を丸めること（四捨五入または偶数への丸めで良い）。補完実施後、各項目について欠損が生じていないことも確認すること。

---
> R-084: 顧客データ（df_customer）の全顧客に対して全期間の売上金額に占める2019年売上金額の割合を計算し、新たなデータを作成せよ。ただし、売上実績がない場合は0として扱うこと。そして計算した割合が0超のものを抽出し、結果を10件表示せよ。また、作成したデータに欠損が存在しないことを確認せよ。

---
> R-085: 顧客データ（df_customer）の全顧客に対し、郵便番号（postal_cd）を用いてジオコードデータ（df_geocode）を紐付け、新たな顧客データを作成せよ。ただし、1つの郵便番号（postal_cd）に複数の経度（longitude）、緯度（latitude）情報が紐づく場合は、経度（longitude）、緯度（latitude）の平均値を算出して使用すること。また、作成結果を確認するために結果を10件表示せよ。

---
> R-086: 085で作成した緯度経度つき顧客データに対し、会員申込店舗コード（application_store_cd）をキーに店舗データ（df_store）と結合せよ。そして申込み店舗の緯度（latitude）・経度情報（longitude)と顧客住所（address）の緯度・経度を用いて申込み店舗と顧客住所の距離（単位：km）を求め、顧客ID（customer_id）、顧客住所（address）、店舗住所（address）とともに表示せよ。計算式は以下の簡易式で良いものとするが、その他精度の高い方式を利用したライブラリを利用してもかまわない。結果は10件表示せよ。

$$
\mbox{緯度（ラジアン）}：\phi \\
\mbox{経度（ラジアン）}：\lambda \\
\mbox{距離}L = 6371 * \arccos(\sin \phi_1 * \sin \phi_2
+ \cos \phi_1 * \cos \phi_2 * \cos(\lambda_1 − \lambda_2))
$$

---
> R-087: 顧客データ（df_customer）では、異なる店舗での申込みなどにより同一顧客が複数登録されている。名前（customer_name）と郵便番号（postal_cd）が同じ顧客は同一顧客とみなして1顧客1レコードとなるように名寄せした名寄顧客データを作成し、顧客データの件数、名寄顧客データの件数、重複数を算出せよ。ただし、同一顧客に対しては売上金額合計が最も高いものを残し、売上金額合計が同一もしくは売上実績がない顧客については顧客ID（customer_id）の番号が小さいものを残すこととする。

---
> R-088: 087で作成したデータを元に、顧客データに統合名寄IDを付与したデータを作成せよ。ただし、統合名寄IDは以下の仕様で付与するものとする。
>
> - 重複していない顧客：顧客ID（customer_id）を設定
> - 重複している顧客：前設問で抽出したレコードの顧客IDを設定
> 
> 顧客IDのユニーク件数と、統合名寄IDのユニーク件数の差も確認すること。

---
> R-089: 売上実績がある顧客を、予測モデル構築のため学習用データとテスト用データに分割したい。それぞれ8:2の割合でランダムにデータを分割せよ。

---
> R-090: レシート明細データ（df_receipt）は2017年1月1日〜2019年10月31日までのデータを有している。売上金額（amount）を月次で集計し、学習用に12ヶ月、テスト用に6ヶ月の時系列モデル構築用データを3セット作成せよ。

---
> R-091: 顧客データ（df_customer）の各顧客に対し、売上実績がある顧客数と売上実績がない顧客数が1:1となるようにアンダーサンプリングで抽出せよ。

---
> R-092: 顧客データ（df_customer）の性別について、第三正規形へと正規化せよ。

---
> R-093: 商品データ（df_product）では各カテゴリのコード値だけを保有し、カテゴリ名は保有していない。カテゴリデータ（df_category）と組み合わせて非正規化し、カテゴリ名を保有した新たな商品データを作成せよ。

---
> R-094: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|有り|UTF-8|
> 
> ファイル出力先のパスは以下のようにすること
> 
> |出力先|
> |:--:|
> |./data|

---
> R-095: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|有り|CP932|
> 
> ファイル出力先のパスは以下のようにすること。
> 
> |出力先|
> |:--:|
> |./data|

---
> R-096: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|無し|UTF-8|
> 
> ファイル出力先のパスは以下のようにすること
> 
> |出力先|
> |:--:|
> |./data|

---
> R-097: 094で作成した以下形式のファイルを読み込み、データを3件を表示させて正しく取り込まれていることを確認せよ。
> 
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|有り|UTF-8|

---
> R-098: 096で作成した以下形式のファイルを読み込み、データを3件を表示させて正しく取り込まれていることを確認せよ。
> 
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|ヘッダ無し|UTF-8|

---
> R-099: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |TSV（タブ区切り）|有り|UTF-8|
> 
> ファイル出力先のパスは以下のようにすること
> 
> |出力先|
> |:--:|
> |./data|

---
> R-100: 099で作成した以下形式のファイルを読み込み、データを3件を表示させて正しく取り込まれていることを確認せよ。
> 
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |TSV（タブ区切り）|有り|UTF-8|

# これで１００本終わりです。おつかれさまでした！